# NB: this is yaml, but with special modifications that only work within
# NDS, namely the !gettext keyword.

# This handles language name translation, and ISO transforms. When
# adding new languages for dictionaries, their names will need to appear
# here; and when adding new languages as internationalisation languages,
# their names will need to be here too.
#
# 1. `isos_to_names` - Pairs of ISOs and language names marked for translation, such
#    that a line appears in each *.po file, where the names will be
#    translated
#
# 2. `isos_to_demonym` - Pairs of ISOs and language names in
#    the language itself. These names will be used in the localisations menu on the site.
#
# 3. `iso_transforms` - sometimes ISOs need to be transformed between
#    2-character format and 3-character format, so if a language has a
#    2-character version, we need the other as well.


# TODO: put these in individual project conf files
# .py: ISO_DISPLAY_RELABELS
iso_display_relabels:
  'crk':      'crk'
  'crk_Macr': 'āēīō'
  'crk_Syll': 'ᓀᐦᐃᔭᐍᐏᐣ'


# .py: NAMES
# these names will be used to generate localization files
isos_to_names:
  # sanit
  "sme": !gettext "North Sámi"
  "se": !gettext "North Sámi"
  "SoMe": !gettext "North Sámi (#SoMe)"
  "en": !gettext "English"
  "hun": !gettext "Hungarian"
  "smj": !gettext "Lule Sámi"
  "spa": !gettext "Spanish"

  # baakoeh
  "sma": !gettext "South Sámi"

  # kyv
  "kpv": !gettext "Komi"
  "kpvS": !gettext "Komi"
  "udm": !gettext "Udmurt"
  "udmM": !gettext "Udmurt"
  "koi": !gettext "Komi-Permyak"

  # sanat
  "fkv": !gettext "Kven"
  "olo": !gettext "Olonetsian"
  "est": !gettext "Estonian"

  # sonad
  "liv": !gettext "Livonian"
  "livM": !gettext "Livonian"
  "izh": !gettext "Izhorian"
  "vep": !gettext "Veps"
  "vro": !gettext "Võro"
  "vot": !gettext "Votic"

  # valks
  "myv": !gettext "Erzya"
  "mdf": !gettext "Moksha"
  "fra": !gettext "French"
  "deu": !gettext "German"

  # muter
  "mrj": !gettext "Western Mari"
  "mhr": !gettext "Eastern Mari"

  # vada
  "yrk": !gettext "Nenets"
  "mns": !gettext "Northern Mansi"

  # saan
  "sms": !gettext "Skolt Sami"
  "smsM": !gettext "Skolt Sami"

  # itwewina
  "crk": !gettext "Plains Cree"
  "crkM": !gettext "Plains Cree"

  # gunaha
  "srs": !gettext "Tsuut'ina"

  # kidwinan
  "otw": !gettext "Odawa"

  # dikaneisdi
  "chr": !gettext "Cherokee"
  "chrL": !gettext "Cherokee"

  # guusaaw
  "hdn": !gettext "Northern Haida"
  "hdnM": !gettext "Northern Haida"

  # saanih
  "smn": !gettext "Inari Saami"

  # bahkogirrje
  "sje": !gettext "Pite Saami"

  # ndstesting
  "kca": !gettext "Khanty"
  # ndstesting
  "gle": !gettext "Irish"

  # target languages
  "fin": !gettext "Finnish"
  "nob": !gettext "Norwegian"

  "ru": !gettext "Russian"
  "rus": !gettext "Russian"

  "fi": !gettext "Finnish"
  "no": !gettext "Norwegian"
  "nob": !gettext "Norwegian"
  "lv": !gettext "Latvian"
  "lav": !gettext "Latvian"
  "eng": !gettext "English"
  "en": !gettext "English"
  "hdn": !gettext "Haida"
  "fra": !gettext "French"
  "deu": !gettext "German"
  "ron": !gettext "Romanian"
  "fit": !gettext "Meänkieli"
  "swe": !gettext "Swedish"
  "sv": !gettext "Swedish"


# These will show up in the localization menu, or wherever the
# language's own name needs to be visible. If the language
# also has a two-character ISO, that will need to be listed too.

# (.py: LOCALISATION_NAMES_BY_LANGUAGE)
isos_to_demonym:
  "sme": "Davvisámegiella"
  "se": "Davvisámegiella"
  "sma": "Åarjelsaemien gïele"
  "ru": "Русский"
  "olo": "Livvin kieli"
  "no": "Norsk"
  "nob": "Norjan kieli"
  "myv": "Эрзянь кель"
  "mdf": "Мокшень кяль"
  "mrj": "Кырык мары йӹлмӹ"
  "yrk": "Ненэцяʼ вада"
  "lv": "Latviešu valoda"
  "lav": "Latviešu valoda"
  "liv": "Līvõ kēļ"
  "kpv": "Коми кыв"
  "kv": "Коми кыв"
  "kpvS": "Коми кыв (Молодцов ортография)"
  "koi": "Коми кыв (Перымса коми)"
  "udm": "Удмурт кыл"
  "izh": "Ižoran keel"
  "fkv": "Kveenin kieli"
  "fi": "Suomi"
  "fin": "Suomen kieli"
  "crk": "nêhiyawêwin"
  "crk_Macr": "nēhiyawēwin"
  "crk_Syll": "ᓀᐦᐃᔭᐍᐏᐣ"
  "eng": "English"
  "et": "Eesti"
  "est": "Eesti"
  "sms": "sääʹmǩiõll"
  "smn": "Anarâškielâ"
  "hdn": "X̲aat Kíl"
  "hdnM": "X̲aat Kíl"
  "en": "English"
  "fr": "Français"
  "hun": "Magyar"
  "hu": "Magyar"
  "chr": "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"
  "sje": "Pite"

  "vep": "Vepsän kel’"
  "vro": "Võro kiilʼ"
  "vot": "Vad̕d̕a čeeli"

  "deu": "Deutsch"
  "ron": "Română"
  "fit": "Meänkieli"
  "sv": "Svenska"
  "swe": "Svenska"

  # ndstesting
  "kca": "ханты ясаӈ"
  "gle": "Gaeilge"


# Only put the exceptional ISOs here
# .py: ISO_TRANSFORMS
iso_transforms:
  "se": "sme"
  "no": "nob"
  "fi": "fin"
  "en": "eng"
  "et": "est"
  "lv": "lav"
  "fr": "fra"
  "de": "deu"
  "kv": "kpv"
  "hu": "hun"
  "ro": "ron"
  "sv": "swe"
